### ISSUE TITLE
DeltaStream only allows 1 stream to be consumed at a time

### ISSUE THREAD

**Issue by oliversong** [nylas/nylas-nodejs#15] opened 2015-08-05 07:46 UTC
When trying to listen for deltas on multiple accounts, it seems like all accounts are bottlenecked through the same connection.

Furthermore, the total throughput when running with multiple accounts is dramatically lower than running with one account. Seems as though there's some non-trivial switching cost.

**Comment by khamidou** [comment] 2015-08-05 15:00
Hi Oliver,

This is weird. I double-checked the code and we’re not doing anything crazy (i.e: we’re creating separate connections to the API, etc.). I also wrote a small test program to try to reproduce the behavior you’re seeing locally. Basically, it simulatenously fetches the 2000 first deltas from the API. I’ve run it with various numbers of accounts and I couldn’t notice a slowdown. 

Could you send me a snippet of your code? It would be very helpful.

regards, 

Karim


The test program, for reference:
```javascript
global.Nylas = require('nylas').config({
    appId: ‘local_test’,
    appSecret: 'local_test’,
    apiServer: 'http://localhost:5555'
});

var MAX_COUNT = 2000;
var total_count = 0;

Nylas.with('emptyToken').namespaces.list({}, function(err, namespaces){
    var ns1 = namespaces[0];

    ns1.deltas.generateCursor(0, function(error, cursor) {
      // Start the stream and add event handlers.
      var stream = ns1.deltas.startStream(cursor);
      stream.on('delta', function(delta) {
        // Handle the new delta here.
        total_count++;
        if (total_count == MAX_COUNT) {
            process.exit();
        }
      }).on('error', function(err) {
        // Handle errors here, such as by restarting the stream at the last cursor.
        console.error('Delta streaming error:', err);

      });
    });

});

Nylas.with('emptyToken').namespaces.list({}, function(err, namespaces){
    var ns2 = namespaces[1];
    ns2.deltas.generateCursor(0, function(error, cursor) {
        // Start the stream and add event handlers.
        var stream2 = ns2.deltas.startStream(cursor);

        stream2.on('delta', function(delta) {
          total_count++;
          if (total_count == MAX_COUNT) {
            process.exit();
          }
        }).on('error', function(err) {
          // Handle errors here, such as by restarting the stream at the last cursor.
          console.error('Delta streaming error:', err);

        });
      });
});

Nylas.with('emptyToken').namespaces.list({}, function(err, namespaces){
    var ns2 = namespaces[2];
    ns2.deltas.generateCursor(0, function(error, cursor) {
        // Start the stream and add event handlers.
        var stream2 = ns2.deltas.startStream(cursor);

        stream2.on('delta', function(delta) {
          // Handle the new delta here.
          total_count++;
          if (total_count == MAX_COUNT) {
            process.exit();
          }
        }).on('error', function(err) {
          // Handle errors here, such as by restarting the stream at the last cursor.
          console.error('Delta streaming error:', err);

        });
      });
});

Nylas.with('emptyToken').namespaces.list({}, function(err, namespaces){
    var ns2 = namespaces[3];
    ns2.deltas.generateCursor(0, function(error, cursor) {
        // Start the stream and add event handlers.
        var stream2 = ns2.deltas.startStream(cursor);

        stream2.on('delta', function(delta) {
          total_count++;
          if (total_count == MAX_COUNT) {
            process.exit();
          }
        }).on('error', function(err) {
          // Handle errors here, such as by restarting the stream at the last cursor.
          console.error('Delta streaming error:', err);

        });
      });
});
```

**Comment by oliversong** [comment] 2015-08-05 19:12
Hey @khamidou, just curious, what version of node are you using?

**Comment by khamidou** [comment] 2015-08-05 19:20
I'm running v0.12.6 on Ubuntu.

**Comment by bengotow** [comment] 2015-08-07 19:43
Hi @oliversong — sorry you're having trouble! I'm a javascript engineer at Nylas. I ran your example gist (https://gist.github.com/oliversong/e65d3cc7928988ef295a) in Node v0.12.7 through the profiler in node-inspector v0.12.2.

Concurrency 2:
![concurrency 2](https://cloud.githubusercontent.com/assets/1037212/9144384/6d18b9e6-3d01-11e5-9361-64f498fc594d.png)

Concurrency 30:
![concurrency 30](https://cloud.githubusercontent.com/assets/1037212/9144382/6abaa57e-3d01-11e5-91e4-a58dd9c3a62c.png)

From these tests, it doesn't seem we're maxing out the CPU doing JSON processing, etc.

I also restructured the gist a bit—I noticed that with a large number of connections, it takes a good amount of time for all of them to connect and start streaming. "First to 5000 deltas" might not be the best metric to measure. I changed it to continue streaming indefinitely, and sample "number of deltas received" every five seconds, then compute a rolling average of the last five samples to give an average number of deltas received over 25 seconds.

Here's my updated script: https://gist.github.com/bengotow/2f1333683010230b6d91

In my tests, the rolling average is comparable between 2 workers and 20 workers. It varies quite a bit, which might be due to the fact that delta payloads vary in size pretty significantly (since they include message bodies). Would be interesting to do some further tests looking at total kb/s.

```
ip-192-168-128-244:test-concurrency bengotow$ 
ip-192-168-128-244:test-concurrency bengotow$ node --debug app.js 
Debugger listening on port 5858
Running 2 assistants concurrently
Opening stream 1
Opening stream 0
Deltas in last 5000 msec: 1. Rolling average of 5 samples: 0.2
Deltas in last 5000 msec: 690. Rolling average of 5 samples: 138.16
Deltas in last 5000 msec: 1257. Rolling average of 5 samples: 361.928
Deltas in last 5000 msec: 1222. Rolling average of 5 samples: 533.9424
Deltas in last 5000 msec: 763. Rolling average of 5 samples: 579.75392
Deltas in last 5000 msec: 992. Rolling average of 5 samples: 662.203136
Deltas in last 5000 msec: 286. Rolling average of 5 samples: 586.9625088
Deltas in last 5000 msec: 42. Rolling average of 5 samples: 477.97000704000004
Deltas in last 5000 msec: 484. Rolling average of 5 samples: 479.17600563200006
Deltas in last 5000 msec: 896. Rolling average of 5 samples: 562.5408045056001
Deltas in last 5000 msec: 927. Rolling average of 5 samples: 635.4326436044802
Deltas in last 5000 msec: 731. Rolling average of 5 samples: 654.5461148835842
Deltas in last 5000 msec: 776. Rolling average of 5 samples: 678.8368919068674
Deltas in last 5000 msec: 1387. Rolling average of 5 samples: 820.469513525494
Deltas in last 5000 msec: 1161. Rolling average of 5 samples: 888.5756108203952
```

```
ip-192-168-128-244:test-concurrency bengotow$ node --debug app.js 
Debugger listening on port 5858
Running 20 assistants concurrently
Opening stream 3
Opening stream 6
Opening stream 0
Opening stream 1
Opening stream 8
Opening stream 19
Opening stream 16
Opening stream 5
Opening stream 10
Opening stream 4
Opening stream 12
Opening stream 14
Opening stream 9
Opening stream 17
Opening stream 11
Opening stream 2
Opening stream 7
Opening stream 18
Opening stream 15
Opening stream 13
Deltas in last 5000 msec: 1. Rolling average of 5 samples: 0.2
Deltas in last 5000 msec: 881. Rolling average of 5 samples: 176.36
Deltas in last 5000 msec: 716. Rolling average of 5 samples: 284.288
Deltas in last 5000 msec: 306. Rolling average of 5 samples: 288.6304
Deltas in last 5000 msec: 338. Rolling average of 5 samples: 298.50432
Deltas in last 5000 msec: 738. Rolling average of 5 samples: 386.403456
Deltas in last 5000 msec: 1015. Rolling average of 5 samples: 512.1227648
Deltas in last 5000 msec: 1071. Rolling average of 5 samples: 623.89821184
Deltas in last 5000 msec: 1052. Rolling average of 5 samples: 709.5185694720001
Deltas in last 5000 msec: 920. Rolling average of 5 samples: 751.6148555776001
Deltas in last 5000 msec: 1096. Rolling average of 5 samples: 820.4918844620802
Deltas in last 5000 msec: 1059. Rolling average of 5 samples: 868.1935075696642
Deltas in last 5000 msec: 925. Rolling average of 5 samples: 879.5548060557314
Deltas in last 5000 msec: 780. Rolling average of 5 samples: 859.6438448445851
Deltas in last 5000 msec: 712. Rolling average of 5 samples: 830.1150758756681
```

**Comment by jackiehluo** [comment] 2017-10-23 22:51
Closing this issue, since we don't have further information.

**Closed by jackiehluo** 2017-10-23 22:51 UTC
