### ISSUE TITLE
Get account object no "nylas.account" method

### ISSUE THREAD

**Issue by slava-tre** [nylas/nylas-nodejs#35] opened 2016-05-10 18:26 UTC
Still can't retrieve a account data by using current Nylas driver with a method:

```
nylas.account.get().then(function(model) {
    console.log(model);
});
```

Having a error as:
`Cannot read property 'get' of undefined` 

`nylas.account` is undefined

BTW: The issue was already created here https://github.com/nylas/nylas-nodejs/issues/29
any updates?

**Comment by emarthinsen** [comment] 2016-05-12 04:00
I'm running into the exact same issue.

**Comment by emarthinsen** [comment] 2016-05-12 04:31
The problem is that Nylas hasn't released this module in a while. The version on npm lags behind and doesn't have the nylas.account method. It's not entirely safe, but you could do this to use the latest code:

`npm install git+https://git@github.com/nylas/nylas-nodejs --save`

Nylas, any chance of pushing out the latest code to NPM?

**Comment by khamidou** [comment] 2016-05-12 17:15
Just a quick heads up --- I'm looking into this.

Thanks,

k

**Comment by gunar** [comment] 2016-05-18 21:05
Any development? :innocent:

**Comment by spang** [comment] 2017-10-10 23:59
This has been fixed on npm for some time now

**Closed by spang** 2017-10-10 23:59 UTC
