### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by anosov-otg** [nylas/nylas-nodejs#223] opened 2021-04-28 09:39 UTC
Hey, guys!

I have an issue with the latest 5.3.3 version of this lib. Specifically, I'm doing this:

```typescript
const nylas = Nylas.config({clientId: "myclientid", clientSecret: "mysecret"}).with("mytoken");
const calendars = await nylas.calendars.list();
```

But request fails in Chrome (latest) and I see this error in a console:

```
Access to fetch at 'https://api.nylas.com/calendars?offset=0&limit=100' from origin 'https://localhost:3000' has been blocked by CORS policy: Request header field nylas-api-version is not allowed by Access-Control-Allow-Headers in preflight response.
```

Which means that the OPTIONS request has all requested headers in the response's Access-Control-Allow-Headers header, except `nylas-api-version` header. And this looks like either an api server misconfiguration or an issue in the library.

I tried [patch-package](https://github.com/ds300/patch-package) and for now solved issue locally by the following patch which removes nylas-api-version header. All works good for me with this patch.

```
diff --git a/node_modules/nylas/lib/nylas-connection.js b/node_modules/nylas/lib/nylas-connection.js
index 636c310..aacd6ef 100755
--- a/node_modules/nylas/lib/nylas-connection.js
+++ b/node_modules/nylas/lib/nylas-connection.js
@@ -103,7 +103,6 @@ var NylasConnection = /** @class */ (function () {
             if (newOptions.headers['User-Agent'] == null) {
                 newOptions.headers['User-Agent'] = "Nylas Node SDK v" + SDK_VERSION;
             }
-            newOptions.headers['Nylas-API-Version'] = SUPPORTED_API_VERSION;
             newOptions.headers['Nylas-SDK-API-Version'] = SUPPORTED_API_VERSION;
             newOptions.headers['X-Nylas-Client-Id'] = this.clientId;
         }
```

But the question is: do we really need that header? If yes, probably api server should be fixed. If not, the library should be fixed. Or am I doing something wrong?

Thanks.

**Comment by dereekb** [comment] 2021-05-24 00:19
Correct me if I'm wrong, but are you using this library in a browser web app directly? This is a library for a NodeJS backend, as a result I don't think what you're trying to do is supported. (If you're making a web app for public consumption you shouldn't have your Nylas Secret token published to a frontend)

Anyways, the CORS rules you're running into are security features that are working as intended in Chrome and other people's browsers. If you're using this for your own project and only running it in your browser you can disable CORS requests.

This StackOverflow post explains it and has additional resources: https://stackoverflow.com/a/54563590

 If you're building an app for others to use, you'll want to build a backend that your frontend communicates with and handles the requests to Nylas securely.

**Comment by anosov-otg** [comment] 2021-05-24 14:02
well, let's consider this is for my pet project
yet, I still don't want to disable CORS
and yes, I'm seeing this issue in Chrome

The point is: library does send `Nylas-API-Version` header in its requests, whereas `Access-Control-Allow-Headers` returned by the backend doesn't include it. I suppose either backend should list `Nylas-API-Version` as allowed in its response OR library should not send it.

**Comment by dereekb** [comment] 2021-05-24 17:08
That makes sense to me, you're right. Sure enough the headers I got back from Nylas:

```
Access-Control-Allow-Headers 

Authorization,Accept,Cache-Control,X-Requested-With,Content-Type,User-Agent,Nylas-SDK-API-Version,X-Nylas-Client-Id
```

I'm guessing the header may have changed and was dropped at some point.

**Comment by anosov-otg** [comment] 2021-05-24 17:24
> I'm guessing the header may have changed and was dropped at some point.

Right, that's what I think too. But it better be fixed and sounds like an easy fix to me. I would even suggest a patch, but am not sure if it should be a library or a backend fix.

**Comment by mrashed-dev** [comment] 2021-06-09 21:28
Hey @anosov-otg! Thanks for opening this issue, we are investigating and we will get back to you shortly regarding this.

**Comment by mrashed-dev** [comment] 2021-06-11 20:12
@anosov-otg Thanks for bringing this issue to light. The `Nylas-API-Version` header is _indeed_ a valid header. However, you are correct in your investigation - it is not whitelisted in the `Access-Control-Allow-Headers`. We have a ticket internally for this issue, and I have passed it on to the correct team that will continue to investigate why it's not whitelisted and get to a solution. Since this isn't Node SDK specific, I'm going to close this issue however I will update this issue once there's been a resolution internally. Thank you!

**Closed by mrashed-dev** 2021-06-11 20:12 UTC

**Comment by 8bitjoey** [comment] 2021-12-16 06:37
@mrashed-dev do you have any news regarding this issue? seems like the issue is still not solved internally
